name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and release ARM templates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Bake version in templates
        id: template_versioning
        run: |
          sed -i "s/var templateVersion = '0.0.0'/var templateVersion = '${{ env.VERSION }}'/" deployment/templates/main.bicep
          sed -i "s/var templateVersion = '0.0.0'/var templateVersion = '${{ env.VERSION }}'/" deployment/templates/linked/vmCreationBatch.bicep

      - name: Link vmCreationBatchTemplateUri in main template
        id: vmcreationbatchuri_link
        run: |
          sed -i "s|\[\[param:vmCreationBatchTemplateUri\]\]|https://github.com/schoolyear/avd-deployments/releases/download/${{ env.VERSION }}/vmCreationBatch.json|" deployment/templates/main.bicep

      - name: Output directory
        run: mkdir -p out

      - name: Build main deployment template
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: deployment/templates/main.bicep
          outputFilePath: out/main.json

      - name: Build vmCreationBatch
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: deployment/templates/linked/vmCreationBatch.bicep
          outputFilePath: out/vmCreationBatch.json

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            out/main.json
            out/vmCreationBatch.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
